Update Schema Automatically
NASA-PDS/pds-registry-mgr-elastic pull request #23
Opened 2021-05-05 15:54 UTC by tdddblog

See https://github.com/NASA-PDS/pds-registry-app/issues/146

2021-05-13 19:04 UTC, tloubrieu-jpl requested changes
Hi @tdddblog ,

I was not able to make the test procedure you describe work:

S./bin/registry-manager load-data -dir ~/tmp/son_pere                                  less /Users/loubrieu/tmp/sElasticsearch URL: http://localhost:9200
            Index: registry

Updating schema with fields from /Users/loubrieu/tmp/son_pere/fields.txt
[ERROR] Could not find datatype for field 'orex:Time/orex:start_sclk'.
See 'https://nasa-pds.github.io/pds-registry-app/operate/common-ops.html#Load' for more information.

I am using this harvest configuration 
[bundles.xml.zip](https://github.com/NASA-PDS/pds-registry-mgr-elastic/files/6474547/bundles.xml.zip)

2021-05-15 00:23 UTC, tdddblog commented on src/main/java/gov/nasa/pds/registry/mgr/dd/parser/AttributeDictionaryParser.java
> + * Parses "dataDictionary" -> "attributeDictionary" subtree.
Javadocs are fixed

2021-05-15 00:36 UTC, tdddblog commented
To troubleshoot your issue with OREX schema I need all files from your Harvest output directory. Can you zip it and attach or email to me. Also can you please provide full log for "registry-manager load-data" command.

2021-05-18 17:09 UTC, tloubrieu-jpl commented
> To troubleshoot your issue with OREX schema I need all files from your Harvest output directory. Can you zip it and attach or email to me. Also can you please provide full log for "registry-manager load-data" command.

That is my mistake, I used an older version of the registry-manager. This works with the current version

2021-05-18 17:12 UTC, tloubrieu-jpl approved these changes
mvn javadoc:jar works now

2021-05-18 17:12 UTC, merged